FROM rjd_part1
# Second Dockerfile applys runtime script and other specializations.

COPY assets/runtime/run.sh /runtime/run.sh

COPY assets/iniforum/*.sh $TENDENCI_INSTALL_DIR
RUN chmod +x $TENDENCI_INSTALL_DIR/*.sh

VOLUME "$TENDENCI_PROJECT_ROOT" "$TENDENCI_LOG_DIR"

WORKDIR "$TENDENCI_INSTALL_DIR"

ENTRYPOINT [ "/bin/bash" ]
CMD [ "/runtime/run.sh" ]
