FROM rjd_part1
# Second Dockerfile applys runtime script and other specializations.

COPY assets/runtime/run.sh /runtime/run.sh

VOLUME "$TENDENCI_PROJECT_ROOT" "$TENDENCI_LOG_DIR"

WORKDIR "$TENDENCI_INSTALL_DIR"

ENTRYPOINT [ "/bin/bash" ]
CMD [ "/runtime/run.sh" ]

# run user with restricted (non root) privileges 2023-08-22 08:53:20 rjd
# RUN useradd -ms /bin/bash tendenci
# USER tendenci